-- MySQL Script generated by MySQL Workbench
-- jeu. 06 juin 2019 09:51:50 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema yoship
-- ------------------- ----------------------------------

-- -----------------------------------------------------
-- Schema yoship
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yoship` DEFAULT CHARACTER SET utf8 ;
USE `yoship` ;

-- -----------------------------------------------------
-- Table `yoship`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoship`.`users` (
   -- AUTO_INCREMENT
  `id` INT NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `name` VARCHAR(32) NOT NULL,
  `firstname` VARCHAR(32) NOT NULL,
  `pseudo` VARCHAR(32) NOT NULL,
  `dateOfBirth` VARCHAR(32) NOT NULL,
  `mail` VARCHAR(32) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
   -- FILE
  `picture` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `address` VARCHAR(128) NULL,
  `postcode` INT(10) NULL,
  `city` VARCHAR(64) NULL,
  `country` VARCHAR(64) NULL,
  `role` VARCHAR(20) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` DATETIME NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT true,
  `docVerified` TINYINT(1) NULL DEFAULT 1,
  `emailVerified` TINYINT(1) NOT NULL DEFAULT 0,
	
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `uuid_UNIQUE` ON `yoship`.`users` (`uuid` ASC);

CREATE UNIQUE INDEX `mail_UNIQUE` ON `yoship`.`users` (`mail` ASC);


-- -----------------------------------------------------
-- Table `yoship`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoship`.`cars` (
   -- AUTO_INCREMENT
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(256) NOT NULL,
  `brand` VARCHAR(32) NOT NULL,
  `modelYear` DATETIME NOT NULL,
  `kilometers` VARCHAR(6) NOT NULL,
  `horsepower` VARCHAR(3) NOT NULL,
  `licencePlate` VARCHAR(16) NOT NULL,
  `color` VARCHAR(64) NOT NULL,
  `fuel` VARCHAR(16) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_cars_ibfk_1` ON `yoship`.`cars` (`userId` ASC);

ALTER TABLE cars ADD FOREIGN KEY (userId) REFERENCES users (uuid);

CREATE UNIQUE INDEX `licencePlate_UNIQUE` ON `yoship`.`cars` (`licencePlate` ASC);


-- -----------------------------------------------------
-- Table `yoship`.`enterpriseInformations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoship`.`enterpriseInformations` (
   -- AUTO_INCREMENT
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(256) NOT NULL,
  `nSiret` VARCHAR(16) NULL,
  `address` VARCHAR(128) NOT NULL,
  `postcode` INT(10) NOT NULL,
  `city` VARCHAR(64) NOT NULL,
  `country` VARCHAR(64) NOT NULL,
  `numberOfEmployees` INT(6) NULL,
   -- FILE
  `picture` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_enterpriseInformations_user_idx` ON `yoship`.`enterpriseInformations` (`userId` ASC);
ALTER TABLE enterpriseInformations ADD FOREIGN KEY (userId) REFERENCES users (uuid);

CREATE UNIQUE INDEX `nSiret_UNIQUE` ON `yoship`.`enterpriseInformations` (`nSiret` ASC);

CREATE UNIQUE INDEX `mail_UNIQUE` ON `yoship`.`enterpriseInformations` (`mail` ASC);


-- -----------------------------------------------------
-- Table `yoship`.`driverCourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoship`.`driverCourse` (
   -- AUTO_INCREMENT
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(256) NOT NULL,
   -- FILE OR BOOLEAN
  `saleTraining` VARCHAR(255) NOT NULL,
   -- FILE OR BOOLEAN
  `fashionDesign` VARCHAR(255) NOT NULL,
   -- FILE OR BOOLEAN
  `englishTraining` VARCHAR(255) NOT NULL,
   -- FILE OR BOOLEAN
  `finalExam` VARCHAR(255) NOT NULL,
   -- FILE OR BOOLEAN
  `driverTraining` VARCHAR(255) NOT NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_driverCourse_user1_idx` ON `yoship`.`driverCourse` (`userId` ASC);
ALTER TABLE driverCourse ADD FOREIGN KEY (userId) REFERENCES users (uuid);


-- -----------------------------------------------------
-- Table `yoship`.`carDocuments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoship`.`carDocuments` (
   -- AUTO_INCREMENT
  `id` INT NOT NULL AUTO_INCREMENT,
  `carId` INT NOT NULL,
   -- FILE
  `technicalControl` VARCHAR(255) NOT NULL,
   -- FILE
  `assurance` VARCHAR(255) NOT NULL,
   -- FILE
  `carRegistrationDoc` VARCHAR(255) NOT NULL,
   -- FILE
  `leasingContract` VARCHAR(255) NOT NULL,
  `updatedAt` DATETIME NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_carDocuments_car1_idx` ON `yoship`.`carDocuments` (`carId` ASC);
ALTER TABLE carDocuments ADD FOREIGN KEY (carId) REFERENCES cars (id);
CREATE UNIQUE INDEX `carId_UNIQUE` ON `yoship`.`carDocuments` (`carId` ASC);

-- -----------------------------------------------------
-- Table `yoship`.`driverStats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoship`.`driverStats` (
   -- AUTO_INCREMENT
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(256) NOT NULL,
  `performanceIndication` FLOAT NOT NULL,
  `progress` FLOAT NOT NULL,
  `averageRate` FLOAT NOT NULL,
  `ratingEvolution` FLOAT NOT NULL,
  `distanceKms` FLOAT NOT NULL,
  `statusEvolution` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_driverStats_ibfk_1` ON `yoship`.`driverStats` (`userId` ASC);

ALTER TABLE driverStats ADD FOREIGN KEY (userId) REFERENCES users (uuid);

CREATE UNIQUE INDEX `userId_UNIQUE` ON `yoship`.`driverStats` (`userId` ASC);

-- -----------------------------------------------------
-- Table `yoship`.`driverPapers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yoship`.`driverPapers` (
   -- AUTO_INCREMENT
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` VARCHAR(256) NOT NULL,
   -- FILE
  `rib` VARCHAR(255) NULL,
   -- FILE
  `driverLicense` VARCHAR(255) NULL,
   -- FILE
  `proofOfResidence` VARCHAR(255) NULL,
   -- FILE
  `identityCard` VARCHAR(255) NULL,
  `nSiret` VARCHAR(16) NULL,
  `updatedAt` DATETIME NULL,
  `isActive` TINYINT(1) NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE INDEX `fk_driverPapers_ibfk_1` ON `yoship`.`driverPapers` (`userId` ASC);
ALTER TABLE driverPapers ADD FOREIGN KEY (userId) REFERENCES users (uuid);

CREATE UNIQUE INDEX `nSiret_UNIQUE` ON `yoship`.`driverPapers` (`nSiret` ASC);
CREATE UNIQUE INDEX `userId_UNIQUE` ON `yoship`.`driverPapers` (`userId` ASC);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
